name: Delete Environment (default settings)

on:
  workflow_dispatch: {}

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ github.token }}
          environment: production
          ref: csmstest
          onlyRemoveDeployments: true
